# all paths will have prefix /api/
#server.servlet.contextPath=/api/*
#debug=true
logging:
  level:
    web: DEBUG
    org.springframework.security: DEBUG
file-paths:
  regionsFilePath: "src/main/resources/regions.yml"
  locationsFilePath: "src/main/resources/locations.yml"
