#server.servlet.contextPath=/api/*
#debug: true
#logging:
#  level:
#    web: DEBUG
#    org.springframework.security: DEBUG

spring:
  h2:
    console:
      enabled: true
  datasource:
    generate-unique-name: false
    url: jdbc:h2:mem:testdb

#logging.level.org.hibernate.SQL: DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
